import { createFileRoute } from '@tanstack/react-router'
import { useEffect, useState } from "react";
import { Background } from "@/components/background/Background";
import { Particles } from "@/components/background/Particles";
import { CustomCursor } from "@/components/cursor/CustomCursor";
import { SmoothScroll } from "@/components/layout/SmoothScroll";
import { ControlDock } from "@/components/layout/ControlDock";

import { Assistant } from "@/components/ai/Assistant";
import { CommandPalette } from "@/components/secret/CommandPalette";
import { Terminal } from "@/components/secret/Terminal";
import { SecretFeatures } from "@/components/secret/SecretFeatures";
import { useCmsStore } from "@/store/useCmsStore";
import { getArticlesFn } from "@/actions/cms";

import { useQuery } from '@tanstack/react-query';

import { WebsiteRenderer } from "@/components/WebsiteRenderer";
import { PortfolioData } from "@/shared/types";
import { PreviewActionBar } from "@/components/layout/PreviewActionBar";

export const Route = createFileRoute("/")({
  component: Index,
  validateSearch: (search: Record<string, unknown>): { preview?: string } => {
    return {
      preview: search.preview as string | undefined,
    }
  }
});

function Index() {
  const [mounted, setMounted] = useState(false);
  const [fallbackBlogs, setFallbackBlogs] = useState<any[]>([]);
  const cmsStore = useCmsStore();

  // Auto-updating query for articles
  const { data: dbArticles } = useQuery({
    queryKey: ['articles'],
    queryFn: () => getArticlesFn(),
    refetchInterval: 10000, // Auto update every 10 seconds
  });

  useEffect(() => {
    setMounted(true);
    
    // Background fetch of latest JSON generated by CMS
    const fetchLatest = async () => {
      try {
        const t = Date.now();
        const fetchJson = async (url: string) => {
          const res = await fetch(url);
          return res.ok ? await res.json() : null;
        };

        const [siteRes, projRes, skillRes, themeRes] = await Promise.all([
          fetchJson(`/generated/site.json?t=${t}`),
          fetchJson(`/generated/projects.json?t=${t}`),
          fetchJson(`/generated/skills.json?t=${t}`),
          fetchJson(`/generated/theme.json?t=${t}`),
        ]);
        
        // Fetch JSON fallback for blogs in case db fails
        const blogRes = await fetchJson(`/generated/blog/index.json?t=${t}`);
        if (blogRes && blogRes.length > 0) setFallbackBlogs(blogRes);

        if (siteRes && Object.keys(siteRes).length > 0) cmsStore.setSite(siteRes);
        if (projRes && projRes.length > 0) cmsStore.setProjects(projRes);
        if (skillRes && skillRes.length > 0) cmsStore.setSkills(skillRes);
        if (themeRes && Object.keys(themeRes).length > 0) cmsStore.setTheme(themeRes);
      } catch (e) {
        console.error("Failed to fetch latest CMS data", e);
      }
    };
    
    fetchLatest();
  }, []);

  const blogsToRender = (dbArticles && dbArticles.length > 0) ? dbArticles : fallbackBlogs;

  const { preview } = Route.useSearch();

  // Construct PortfolioData
  const portfolioData: PortfolioData = {
    profile: cmsStore.site,
    projects: cmsStore.projects,
    experience: (cmsStore as any).experience || [],
    certifications: (cmsStore as any).certifications || [],
    skills: cmsStore.skills,
    blog: blogsToRender,
    contact: cmsStore.site,
    social: cmsStore.site?.socialLinks || [],
    theme: {
      id: preview || cmsStore.theme?.activeTemplate || "bento",
      name: "Template",
      version: "1.0",
      author: "Admin",
      description: "",
      thumbnail: "",
      supports: [],
      settings: cmsStore.theme?.settings || { animations: true }
    }
  };

  return (
    <>
      <Background />
      <Particles />
      {mounted && (
        <>
          <CustomCursor />
          <SmoothScroll />
        </>
      )}

      {/* Control components which might be global */}
      <ControlDock />
      {mounted && (
        <>
          <Assistant />
          <CommandPalette />
          <Terminal />
          <SecretFeatures />
        </>
      )}

      {preview && <PreviewActionBar templateId={preview} />}
      <WebsiteRenderer data={portfolioData} />
    </>
  );
}
