import { createFileRoute } from '@tanstack/react-router'
import { useEffect, useState } from "react";
import { Background } from "@/components/background/Background";
import { Particles } from "@/components/background/Particles";
import { CustomCursor } from "@/components/cursor/CustomCursor";
import { SmoothScroll } from "@/components/layout/SmoothScroll";
import { FloatingNav } from "@/components/layout/FloatingNav";
import { ControlDock } from "@/components/layout/ControlDock";
import { Footer } from "@/components/layout/Footer";
import { Hero } from "@/components/sections/Hero";
import { About } from "@/components/sections/About";
import { Skills } from "@/components/sections/Skills";
import { Projects } from "@/components/sections/Projects";
import { Experience } from "@/components/sections/Experience";
import { Certifications } from "@/components/sections/Certifications";
import { GithubSection } from "@/components/sections/GithubSection";
import { Blog } from "@/components/sections/Blog";
import { Contact } from "@/components/sections/Contact";
import { Assistant } from "@/components/ai/Assistant";
import { CommandPalette } from "@/components/secret/CommandPalette";
import { Terminal } from "@/components/secret/Terminal";
import { SecretFeatures } from "@/components/secret/SecretFeatures";
import { useCmsStore } from "@/store/useCmsStore";
import { getArticlesFn } from "@/actions/cms";

export const Route = createFileRoute("/")({
  component: Index,
});

function Index() {
  const [mounted, setMounted] = useState(false);
  const [blogs, setBlogs] = useState<any[]>([]);
  const { setSite, setProjects, setSkills, setTheme, site } = useCmsStore();

  useEffect(() => {
    setMounted(true);
    
    // Background fetch of latest JSON generated by CMS
    const fetchLatest = async () => {
      try {
        const t = Date.now();
        const fetchJson = async (url: string) => {
          const res = await fetch(url);
          return res.ok ? await res.json() : null;
        };

        const [siteRes, projRes, skillRes, themeRes] = await Promise.all([
          fetchJson(`/generated/site.json?t=${t}`),
          fetchJson(`/generated/projects.json?t=${t}`),
          fetchJson(`/generated/skills.json?t=${t}`),
          fetchJson(`/generated/theme.json?t=${t}`),
        ]);
        
        // Fetch articles dynamically from server function to avoid Vercel ephemeral storage issues
        try {
          const dbArticles = await getArticlesFn();
          if (dbArticles && dbArticles.length > 0) setBlogs(dbArticles);
        } catch (err) {
          console.warn("Failed to fetch dynamic articles, falling back to JSON", err);
          const blogRes = await fetchJson(`/generated/blog/index.json?t=${t}`);
          if (blogRes && blogRes.length > 0) setBlogs(blogRes);
        }

        if (siteRes && Object.keys(siteRes).length > 0) setSite(siteRes);
        if (projRes && projRes.length > 0) setProjects(projRes);
        if (skillRes && skillRes.length > 0) setSkills(skillRes);
        if (themeRes && Object.keys(themeRes).length > 0) setTheme(themeRes);
      } catch (e) {
        console.error("Failed to fetch latest CMS data", e);
      }
    };
    
    fetchLatest();
  }, []);

  return (
    <>
      <Background />
      <Particles />
      {mounted && (
        <>
          <CustomCursor />
          <SmoothScroll />
        </>
      )}

      <FloatingNav />
      <ControlDock />

      <main>
        <Hero />
        <About />
        <Skills />
        <Projects />
        <Experience />
        <Certifications />
        <GithubSection username={site?.github_username || "O-FALLEN-ANGEL-O"} />
        <Blog posts={blogs} />
        <Contact />
      </main>
      <Footer />

      {mounted && (
        <>
          <Assistant />
          <CommandPalette />
          <Terminal />
          <SecretFeatures />
        </>
      )}
    </>
  );
}

